[build]
  functions = "netlify/functions"

[functions]
  included_files = [
    "Minuta clientes Acabadosvis.docx",
    "Contrato clientes visualizza.docx",
    "CON - XXXX - 2026 NOMBRE CLIENTE Gran central.docx"
  ]
